# Generated by Django 2.2.4 on 2019-10-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_repeated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
